// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ddesbyjenwobgcobvjvr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRkZXNieWplbndvYmdjb2J2anZyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg2MTc5NzIsImV4cCI6MjA2NDE5Mzk3Mn0.uH5MRV7UQBWC99kj-K3Yp7AESzNIjPonqa6NfDUDyek";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);